# Generated by Django 5.2 on 2025-04-09 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datacenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datacenter_code', models.CharField(max_length=10, verbose_name='Datacenter Code')),
                ('datacenter_active', models.BooleanField(default=True, verbose_name='Datacenter Active?')),
            ],
        ),
        migrations.CreateModel(
            name='firewall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firewall_name', models.CharField(max_length=50, verbose_name='Firewall Name')),
                ('firewall_active', models.BooleanField(default=True, verbose_name='Firewall Active?')),
                ('firewall_manageip', models.GenericIPAddressField(verbose_name='Management IP')),
                ('firewall_vpnip', models.GenericIPAddressField(verbose_name='VPN Interface IP')),
                ('firewall_user', models.CharField(blank=True, max_length=50, verbose_name='API User')),
                ('firewall_pass', models.CharField(blank=True, max_length=50, verbose_name='API Pass')),
                ('firewall_vpnstatus', models.TextField(blank=True, editable=False)),
                ('firewall_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vpn.datacenter')),
            ],
        ),
    ]
