# Generated by Django 5.2 on 2025-04-10 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_client', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VPNUser',
        ),
    ]
